version: '3.8'

services:

  nginx:
    depends_on:
      - airbnb_app
    links:
      - airbnb_app
    container_name: revproxy
    build: nginx
    # image: nginx:latest
    image: reverse-proxy
    ports:
      - 80:80
    networks:
      - reverse

  airbnb_app:
    build:
      dockerfile: ./Dockerfile
    container_name: airbnb_app
    ports:
      - '3000:3000'
    env_file:
      - .env.prod 
    environment:
      - NODE_ENV=production
      - PORT=3000

  